
package tool.webService.webServiceClient;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TheServiceImplService", targetNamespace = "http://webServiceServer.webService.tool/", wsdlLocation = "http://localhost:8888/myservice?wsdl")
public class TheServiceImplService
    extends Service
{

    private final static URL THESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException THESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName THESERVICEIMPLSERVICE_QNAME = new QName("http://webServiceServer.webService.tool/", "TheServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/myservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        THESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        THESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public TheServiceImplService() {
        super(__getWsdlLocation(), THESERVICEIMPLSERVICE_QNAME);
    }

    public TheServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), THESERVICEIMPLSERVICE_QNAME, features);
    }

    public TheServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, THESERVICEIMPLSERVICE_QNAME);
    }

    public TheServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, THESERVICEIMPLSERVICE_QNAME, features);
    }

    public TheServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TheServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TheService
     */
    @WebEndpoint(name = "TheServiceImplPort")
    public TheService getTheServiceImplPort() {
        return super.getPort(new QName("http://webServiceServer.webService.tool/", "TheServiceImplPort"), TheService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TheService
     */
    @WebEndpoint(name = "TheServiceImplPort")
    public TheService getTheServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webServiceServer.webService.tool/", "TheServiceImplPort"), TheService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (THESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw THESERVICEIMPLSERVICE_EXCEPTION;
        }
        return THESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
